### ISSUE TITLE
prompt-log /some/path gives "invalid signal specification" and seems to ignore argument

### ISSUE THREAD

**Issue by bast** [rkdarst/prompt-log#1]
```console
$ source prompt-log.sh
$ prompt-log /tmp/deleteme.txt

logging to /home/user/demos.out
bash: trap: /tmp/deleteme.txt: invalid signal specification
```

**Comment by bast** [comment]
This is bash 5.1.8.

**Comment by rkdarst** [comment]
So the problem is this:

```shell
alias prompt-log="_prompt-log-enable && trap '_prompt-log-exec-bash' DEBUG"
```

Before I had the main startup function named "prompt-log" and the `trap`
inside of there.  But on the older bash of our cluster, you couldn't
run `trap` inside of a function.  And I think I then found you
couldn't on newer bash, either.  So, I wrapped it in an alias like
this because it seemed more robust, but the downside is the `[file]`
argument just doesn't work anymore.  You might think to wrap it in
another function, but... that breaks for the same reason it didn't
work before..

I guess we could invert the order of `_prompt-log-enable` and `trap`
and see if that works...

Yes, it works (with an extra bit).  Pushing a fix.
